services:
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
  kafka:
    image: confluentinc/cp-kafka:latest
    ports:
      - "9092:9092"
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    depends_on:
      - zookeeper

  gateway:
    build:
      context: .
      dockerfile: ./cmd/gateway/Dockerfile
    container_name: gateway-service
    ports:
      - "8080:8080" # Expose Gateway API on port 8080
    environment:
      - KAFKA_BROKERS=kafka:9092
      - QUIZINTERNAL=quiz:8081
    depends_on:
      - kafka
      - redis
      - quiz

  # Quiz Service
  quiz:
    build:
      context: .
      dockerfile: ./cmd/quiz/Dockerfile
    container_name: quiz-service
    ports:
      - "8081:8081" # Expose Quiz API on port 8081
    environment:
      - KAFKA_BROKERS=kafka:9092
      - REDIS_ADDRESS=redis:6379
    depends_on:
      - kafka
      - redis
